### PR TITLE
fix: fixing asymmetric diamond dependency problem

### PR DESCRIPTION
**Pull request by divdavem**
This is a big refactoring of the algorithm so that the asymmetric diamond dependency problem is fixed:
```ts
const a = writable(0);
const b = derived(a, (a) => `b${a}`);
const c = derived([a, b], ([a, b]) => `${a}${b}`);
const values = [];
const unsubscribe = c.subscribe((value) => values.push(value));
a.set(1);
console.log(values); // displays ["0b0","1b0","1b1"], should display ["0b0","1b1"]
```

For info, the asymmetric diamond dependency bug is also present in svelte stores:
https://svelte.dev/repl/445983f3fdfe4db9ab860d88642f1989?version=3.48.0

A possible workaround (both in ngx-tansu and in svelte stores) is to transform it into the symmetric diamond dependency problem:
```ts
const a = writable(0);
const abis = derived(a, (a) => a); // add a useless level of derived store to work around the issue
const b = derived(a, (a) => `b${a}`);
const c = derived([abis, b], ([a, b]) => `${a}${b}`);
const values = [];
const unsubscribe = c.subscribe((value) => values.push(value));
a.set(1);
console.log(values); // correctly displays ["0b0","1b1"]
```

But it is better to have a proper fix. That's why I am opening this PR!

This PR makes `invalidate` calls recursive so that the whole tree of dependent stores is prevented from updating while values are changed. As a consequence, there is a need of the reverse `revalidate` operation (equivalent to `next` with the same value, but avoiding re-computations) in case the value does not change.
I have not measured the impact on performance in case the tree of dependencies is big. The `invalidate` listener functions should be kept as small and quick as possible (just switching a boolean and propagating the info).

This PR adds several tests for different cases in addition to the asymmetric diamond dependency case.

### CODE REVIEW

**Comment by divdavem** [comment]
@pkozlowski-opensource Feel free to have a look at this PR and to give some feedback if you have time.

**Review by fbasso — APPROVED** [review]
It is fine on my side, but probably need another look from another reviewer. 

@maxokorokov, can you have a look ?

**Comment by pkozlowski-opensource** [comment]
@divdavem oh, cool to see that you are digging into the batched and glitch-free propagation algorithm! I don't think I will have time to do any meaningful review so I don't want to block progress here.

**Comment by divdavem** [comment]
@fbasso Thank you for your review!

**Comment by divdavem** [comment]
> @divdavem oh, cool to see that you are digging into the batched and glitch-free propagation algorithm! I don't think I will have time to do any meaningful review so I don't want to block progress here.

@pkozlowski-opensource Thank you for your comment! It is great to hear from you! I understand you are very busy!
By the way, did you receive my e-mail about npm rights to publish a new version of ngx-tansu?

**Review by maxokorokov — COMMENTED** [review]
LGTM, apart from `invalidate/revalidate` naming.

I find `revalidate` confusing, seems like `uninvalidate` would fit better, but I don't think it's a word. And I don't have better options.

`freeze/unfreeze`, `pause/resume`, `disable/enable`, I don't know...

**Comment by divdavem** [comment]
@maxokorokov Thank you for your review!
I don't know either what names would be the best. I will integrate this PR as it is, then we can rename the functions in a separate PR.

**Pull request merged**
